{   
    'Username': {
        'en': 'Username',
        'de': 'Nutzername',
        'ru': 'Имя пользователя',
        'pt': 'Nome de usuário',
        'nl': 'Gebruikersnaam',
        'fr': "Nom d'utilisateur",
        'it': 'Nome utente',
        'es': 'Nombre de usuario',
        'pl': 'Nazwa Użytkownika',
        'zh-cn': '用户名'
    },
    'bluelink adapter settings': {
        'en': 'Adapter settings for bluelink',
        'de': 'Adaptereinstellungen für bluelink',
        'ru': 'Настройки адаптера для bluelink',
        'pt': 'Configurações do adaptador para bluelink',
        'nl': 'Adapterinstellingen voor bluelink',
        'fr': "Paramètres d'adaptateur pour bluelink",
        'it': "Impostazioni dell'adattatore per bluelink",
        'es': 'Ajustes del adaptador para bluelink',
        'pl': 'Ustawienia adaptera dla bluelink',
        'zh-cn': 'bluelink的适配器设置'
    },
    'Password': {
        'en': 'Password',
        'de': 'Passwort',
        'ru': 'Пароль',
        'pt': 'Senha',
        'nl': 'Wachtwoord',
        'fr': 'Mot de passe',
        'it': "Parola d'ordine",
        'es': 'Contraseña',
        'pl': 'Hasło',
        'zh-cn': '密码'
    },
    'Pin': {
        'en': 'Personal identification number (pin)',
        'de': 'Persönliche Identifikationsnummer (PIN)',
        'ru': 'Персональный идентификационный номер (PIN-код)',
        'pt': 'Número de identificação pessoal (pin)',
        'nl': 'Persoonlijk identificatienummer (pincode)',
        'fr': "Numéro d'identification personnel (pin)",
        'it': 'Numero di identificazione personale (pin)',
        'es': 'Número de identificación personal (pin)',
        'pl': 'Osobisty numer identyfikacyjny (pin)',
        'zh-cn': '个人识别码（图钉）'
    },
    'VIN': {
        'en': 'vehicle identification number (VIN)',
        'de': 'Fahrzeugidentifikationsnummer (VIN)',
        'ru': 'идентификационный номер автомобиля (VIN)',
        'pt': 'número de identificação do veículo (VIN)',
        'nl': 'voertuigidentificatienummer (VIN)',
        'fr': "numéro d'identification du véhicule (VIN)",
        'it': 'numero di identificazione del veicolo (VIN)',
        'es': 'número de identificación del vehículo (VIN)',
        'pl': 'numer identyfikacyjny pojazdu (VIN)',
        'zh-cn': '车辆识别号（VIN）'
    },
    'Brand': {
        'en': 'Brand',
        'de': 'Marke',
        'ru': 'марка',
        'pt': 'marca',
        'nl': 'merk',
        'fr': 'marque',
        'it': 'marca',
        'es': 'marca',
        'pl': 'Marka',
        'zh-cn': '品牌'
    },
    'Request max 400': {
        'en': 'Request per day max 400',
        'de': 'Anfrage pro Tag max 400',
        'ru': 'Запрос в день',
        'pt': 'Pedido por dia max 400',
        'nl': 'Aanvraag per dag max 400',
        'fr': 'Demande par jour max 400',
        'it': 'Richiesta al giorno max 400',
        'es': 'Solicitud por día max 400',
        'pl': 'Żądanie dziennie max 400',
        'zh-cn': '每天请求'
    },
    'Api settings': {
        'en': 'Api settings',
        'de': 'API-Einstellungen',
        'ru': 'Настройки API',
        'pt': 'Configurações de API',
        'nl': 'API-instellingen',
        'fr': "Paramètres de l'API",
        'it': 'Impostazioni API',
        'es': 'Configuración de api',
        'pl': 'Ustawienia API',
        'zh-cn': 'api设置'
    },
    'Account settings': {
        'en': 'Account settings',
        'de': 'Kontoeinstellungen',
        'ru': 'Настройки учетной записи',
        'pt': 'Configurações de Conta',
        'nl': 'Account instellingen',
        'fr': 'Paramètres du compte',
        'it': "Impostazioni dell'account",
        'es': 'Configuraciones de la cuenta',
        'pl': 'Ustawienia konta',
        'zh-cn': '帐号设定'
    },
    'Donate': {
        'en': 'Donate',
        'de': 'Spenden',
        'ru': 'Пожертвовать',
        'pt': 'Doar',
        'nl': 'Doneer',
        'fr': 'Faire un don',
        'it': 'Donare',
        'es': 'Donar',
        'pl': 'Podarować',
        'zh-cn': '捐'
    },
    'donate_desc': {
        'en': "If you like the adapter and want to support the further development, you can thank me with a donation under <a href='https://www.paypal.com/donate?hosted_button_id=AAFQ3WMM46LT8' target='_blank'>PayPal</a>. You are also welcome to send me feature requests for future versions of the adapter.",
        'de': "Wenn Ihnen der Adapter gefällt und Sie die weitere Entwicklung unterstützen möchten, können Sie sich mit einer Spende unter <a href='https://www.paypal.com/donate?hosted_button_id=AAFQ3WMM46LT8' target='_blank'>PayPal</a> bei mir bedanken. Sie können mir auch gerne Funktionsanfragen für zukünftige Versionen des Adapters senden.",
        'ru': "Если вам понравился адаптер и вы хотите поддержать его дальнейшее развитие, вы можете поблагодарить меня, сделав пожертвование в рамках <a href='https://www.paypal.com/donate?hosted_button_id=AAFQ3WMM46LT8' target='_blank'>PayPal</a>. Вы также можете присылать мне запросы функций для будущих версий адаптера.",
        'pt': "Se você gosta do adaptador e deseja apoiar o desenvolvimento posterior, pode me agradecer com uma doação em <a href='https://www.paypal.com/donate?hosted_button_id=AAFQ3WMM46LT8' target='_blank'>PayPal</a>. Você também pode me enviar solicitações de recursos para versões futuras do adaptador.",
        'nl': "Als je de adapter leuk vindt en de verdere ontwikkeling wilt ondersteunen, kun je me bedanken met een donatie onder <a href='https://www.paypal.com/donate?hosted_button_id=AAFQ3WMM46LT8' target='_blank'>PayPal</a>. U kunt mij ook functieverzoeken sturen voor toekomstige versies van de adapter.",
        'fr': "Si vous aimez l'adaptateur et souhaitez soutenir le développement ultérieur, vous pouvez me remercier d'un don sous <a href='https://www.paypal.com/donate?hosted_button_id=AAFQ3WMM46LT8' target='_blank'>PayPal</a>. Vous pouvez également m'envoyer des demandes de fonctionnalités pour les futures versions de l'adaptateur.",
        'it': "Se ti piace l'adattatore e vuoi sostenere l'ulteriore sviluppo, puoi ringraziarmi con una donazione sotto <a href='https://www.paypal.com/donate?hosted_button_id=AAFQ3WMM46LT8' target='_blank'>PayPal</a>. Puoi anche inviarmi richieste di funzionalità per le versioni future dell'adattatore.",
        'es': "Si le gusta el adaptador y desea apoyar el desarrollo posterior, puede agradecerme con una donación en <a href='https://www.paypal.com/donate?hosted_button_id=AAFQ3WMM46LT8' target='_blank'>PayPal</a>. También puede enviarme solicitudes de funciones para futuras versiones del adaptador.",
        'pl': "Jeśli podoba Ci się adapter i chcesz wesprzeć dalszy rozwój, możesz mi podziękować darowizną w ramach <a href='https://www.paypal.com/donate?hosted_button_id=AAFQ3WMM46LT8' target='_blank'>PayPal</a>. Zapraszam również do przesyłania mi próśb o funkcje dotyczące przyszłych wersji adaptera.",
        'zh-cn': "如果您喜欢适配器并希望支持进一步的开发，可以在<a href='https://www.paypal.com/donate?hosted_button_id=AAFQ3WMM46LT8' target='_blank'>PayPal</a>下捐款以表示感谢。也欢迎您向我发送有关适配器将来版本的功能请求。"
    },
    'Receive Daily drive History (EV cars only, needs 3 request per day)': {
        'en': 'Receive Daily drive History (EV cars only, needs 3 request per day)',
        'de': 'Fahrverlauf und Tripinfo abrufen. (nur EV-Autos, benötigt 3 Anfragen pro Tag)',
        'ru': 'Получать ежедневную историю вождения (только для электромобилей, требуется 3 запроса в день)',
        'pt': 'Receber histórico de condução diário (carros EV apenas, precisa de 3 solicitações por dia)',
        'nl': "Dagelijkse rijgeschiedenis ontvangen (alleen EV-auto's, heeft 3 verzoeken per dag nodig)",
        'fr': "Recevez l'historique de conduite quotidien (voitures EV uniquement, nécessite 3 demandes par jour)",
        'it': 'Ricevi la cronologia di guida giornaliera (solo auto EV, richiede 3 richieste al giorno)',
        'es': 'Reciba el historial de conducción diario (solo vehículos eléctricos, se necesitan 3 solicitudes por día)',
        'pl': 'Otrzymuj historię dziennych przejazdów (tylko samochody elektryczne, wymaga 3 żądań dziennie)',
        'zh-cn': '接收每日驾驶历史记录（仅限电动汽车，每天需要 3 个请求）'
    },
    'Stop refresh if 12V battery is under 10.5 V to protect against irreversible damage': {
        'en': 'Stop refresh if 12V battery is under 10.5 V to protect against irreversible damage',
        'de': 'Aktualisierung stoppen, wenn die 12-V-Batterie unter 10,5 V fällt, um irreversible Schäden zu vermeiden',
        'ru': 'Остановите обновление, если напряжение батареи 12 В ниже 10,5 В, для защиты от необратимого повреждения',
        'pt': 'Parar a actualização se a bateria de 12V for inferior a 10,5 V para proteger contra danos irreversíveis',
        'nl': 'Stop verversen als 12V batterij onder 10,5 V is om te beschermen tegen onomkeerbare schade',
        'fr': 'Arrêtez le rafraîchissement si la batterie 12V est inférieure à 10,5 V pour éviter tout dommage irréversible.',
        'it': "Interrompe l'aggiornamento se la batteria da 12 V è inferiore a 10,5 V per evitare danni irreversibili.",
        'es': 'Detiene la actualización si la batería de 12 V está por debajo de 10,5 V para evitar daños irreversibles.',
        'pl': 'Zatrzymanie odświeżania, jeśli napięcie akumulatora 12V jest niższe niż 10,5 V, aby chronić przed nieodwracalnym uszkodzeniem',
        'zh-cn': '如果12V电池低于10.5V，则停止刷新，以防止不可逆的损坏。'
    },
    'ErrorConter':{
        'en': 'Error Counter for restart the adapter after fail connection',
        'de': 'Error Zähler zum Neustart des Adapters nach Verbindungsproblem',
        'ru': 'Ошибка Counter для перезагрузки адаптера после неудачного подключения',
        'pt': 'Contador de erro para reiniciar o adaptador após a conexão de falha',
        'nl': 'Vertaling:',
        'fr': "Compteur d'erreur pour redémarrer l'adaptateur après connexion à défaut",
        'it': "Contatore di errore per riavviare l'adattatore dopo la connessione non riuscita",
        'es': 'Contador de error para reiniciar el adaptador después de la conexión fallida',
        'pl': 'Error Counter do ponownego uruchomienia adapteru po nieudanym połączeniu połączenia',
        'uk': "Помилки для перезавантаження адаптера після з'єднання",
        'zh-cn': '在发生意外之后恢复适应者的行为'
     },
    'App Lang':{
        'en': 'App Language',
        'de': 'App Sprache',
        'ru': 'Language',
        'pt': 'Language',
        'nl': 'Language',
        'fr': 'Language',
        'it': 'Language',
        'es': 'Language',
        'pl': 'Language',
        'zh-cn': 'Language'
      },
    'Resolve the address from coordinates using openstreetmap':{
        "en": "Resolve the address from coordinates using openstreetmap",
        "de": "Lösen Sie die Adresse auf mithilfe der openstreetmap",
        "ru": "Удалить адрес из координат с помощью openstreetmap",
        "pt": "Resolver o endereço das coordenadas usando o openstreetmap",
        "nl": "Oplossen van het adres van coördinaten via openstreetmap",
        "fr": "Résoudre l'adresse des coordonnées en utilisant openstreetmap",
        "it": "Risolvere l'indirizzo dalle coordinate utilizzando openstreetmap",
        "es": "Resolver la dirección desde coordenadas usando openstreetmap",
        "pl": "Rozwiąż adres ze współrzędnych używając mapy openstreetmap",
        "uk": "Вирішити адресу з координат за допомогою openstreetmap",
        "zh-cn": "使用 Opentreetmap 从坐标解析地址"
    }
};
